Add response to the WebDAVClientError type
perry-mitchell/webdav-client pull request #262
Opened 2021-05-13 06:38 UTC by dpakach

Add response property to WebDAVClientError type.

the error handleing is no longer handled by axios (https://github.com/perry-mitchell/webdav-client/blob/master/source/request.ts#L52) so the error object doesn't has access to the HTTP response. this PR fixes that.

2021-05-17 18:10 UTC, perry-mitchell requested changes

2021-05-17 18:10 UTC, perry-mitchell commented on source/response.ts
> +        err.response = response as AxiosResponse;
I'd prefer not to expose Axios-specific properties outside of this library, as I can't guarantee that I'll always use Axios as the request client. Would you consider changing this to `err.response = response` (only) and using the `Response` type in the `WebDAVClientError` interface?

2021-05-18 02:55 UTC, dpakach commented
@perry-mitchell I've fixed it. Please have a look.

2021-05-21 12:31 UTC, perry-mitchell approved these changes

2021-05-21 12:32 UTC, merged