Correctly calculate byte size of the utf8 strings
perry-mitchell/webdav-client pull request #291
Opened 2022-02-17 08:52 UTC by jstastny

The original implementation started causing problems when the webdav client was used in combination with axios 0.22 and later, as in 0.22 axios [started considering the `Content-Length` passed in the request](https://github.com/axios/axios/pull/2880/files#diff-586c04c24608b86a074073c5514cc195be5c4c87ddb56da233f6d998ada4159fR89-R91) where it previously ignored it and calculated the length on its own.

2022-02-25 20:19 UTC, perry-mitchell requested changes

2022-02-25 20:19 UTC, perry-mitchell commented on source/tools/size.ts
> +        return Buffer.byteLength(<string>data);
Unfortunately this won't work, as `Buffer` is not available in the web build.

2022-05-16 03:28 UTC, perry-mitchell commented
Seeing as I didn't get any response, I'll merge and modify this fix to use a library which covers byte-size calculations.

2022-05-16 03:28 UTC, merged

2022-05-16 07:04 UTC, jstastny commented
> 

Hi.

Sorry for not responding. I stopped hoping that this could go live as is, so I've given up.

Thanks for taking the extra step to make it compatible with browser.