Allow providing external HA1 for digest auth
perry-mitchell/webdav-client pull request #333
Opened 2023-01-17 20:17 UTC by manuelottlik

This PR implements #332. It adds nothing but optional parameters for `ha1` and its documentation.

2023-02-06 19:46 UTC, perry-mitchell requested changes
Looks awesome! Just a few items to work out. There's a lot of changes so I'd be surprised if there weren't a few :)

Thanks for this!

2023-02-06 19:46 UTC, perry-mitchell commented on README.md
> +-   Web project bundled with a tool like Webpack that can handle ESM
Any particular reason you change these? `*` are perfectly valid markdown, as are the `|---|` (no spaces) for tables.

2023-02-06 19:46 UTC, perry-mitchell commented on README.md
> +| `withCredentials` | _None_                                                                                    | Credentials inclusion setting for the request,
This is actually harder to read in a width-constricted terminal, when compared to the shortened version that was there before. Are you using some markdown formatting utility perhaps?

2023-02-06 19:46 UTC, perry-mitchell commented on README.md
> +client.createReadStream("/video.mp4").pipe(fs.createWriteStream("~/video.mp4"));
I prefer the stacked format to this..

2023-02-06 19:46 UTC, perry-mitchell commented on README.md
> +fs.createReadStream("~/Music/song.mp3").pipe(client.createWriteStream("/music/song.mp3"));
I prefer the original format

2023-02-06 19:46 UTC, perry-mitchell commented on source/auth/digest.ts
> +    return { username, password, ha1, nc: 0, algorithm: "md5", hasDigestAuth: false };
Would you mind merging/rebasing master? I added formatting (prettier) tests.. want to make sure these changes still pass.

2023-02-06 19:46 UTC, perry-mitchell commented on source/tools/crypto.ts
> +
No need for blank line

2023-02-06 19:46 UTC, perry-mitchell commented on source/types.ts
> +    ha1?: string;
Would you mind sorting this alphabetically?

2023-02-06 19:46 UTC, perry-mitchell commented on source/types.ts
> +    ha1?: string;
Would you mind sorting this alphabetically?

2023-02-06 19:46 UTC, perry-mitchell commented on source/factory.ts
> +        ha1
Would you mind sorting this alphabetically?

2023-02-06 19:46 UTC, perry-mitchell commented on source/factory.ts
> +        ha1
Would you mind sorting this alphabetically?

2023-02-07 16:58 UTC, manuelottlik commented
Hey @perry-mitchell, thank you for the review. All the formatting stuff was not intentional, just some extension – should have payed attention to that, sorry. I will fix all of this, rebase and also order all arguments alphabetically.

2023-02-10 16:27 UTC, manuelottlik commented
Hey @perry-mitchell, I removed all the re-formatting, merged your master into the branch and ordered all arguments alphabetically. Is there anything else I can do?

2023-02-10 17:31 UTC, perry-mitchell commented
I'll check this shortly, thank you!

2023-02-10 19:16 UTC, perry-mitchell approved these changes

2023-02-10 19:18 UTC, merged